addons:
  apt:
    packages:
    - ruby-dev
    - gcc
    - make
    - rpm
before_install:
- gem install fpm
after_install:
- make
deploy:
  provider: releases
  api_key:
    secure: fake_key
  file_glob: true
  file: packages/*
  skip_cleanup: true
  on:
    tags: true
